"""APEX 24/7 — Trading Signal Domain Model.

Deterministic candidate representation.
Signals possess ZERO execution authority and cannot authorize trades.
"""

import math
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from apex.domain.types import SignalDirection, Timeframe
from apex.safety.exceptions import InvalidNumericalDataError


class AIAdvisoryMetadata(BaseModel):
    """Informational AI analysis container.

    CRITICAL INVARIANT: AI output is strictly ADVISORY ONLY.
    It has zero authority to authorize orders, alter risk, or override safety gates.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    model_name: str
    analysis_summary: str
    advisory_confidence: float = Field(ge=0.0, le=1.0)
    context_notes: str = ""
    evidence_tags: list[str] = Field(default_factory=list)


class Signal(BaseModel):
    """Immutable trading signal candidate generated by deterministic detectors.

    A Signal is a proposal. It CANNOT be executed directly.
    Only the Risk Guardian can convert a Signal into an authorized OrderIntent.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    symbol: str
    timeframe: Timeframe
    timestamp_ms: int
    direction: SignalDirection
    trigger_price: float
    suggested_stop_loss: float
    suggested_take_profit: float
    detector_name: str
    detector_version: str
    candle_timestamp_ms: int
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0)
    evidence_metadata: dict[str, Any] = Field(default_factory=dict)
    ai_advisory: AIAdvisoryMetadata | None = None

    @field_validator("symbol")
    @classmethod
    def validate_symbol(cls, v: str) -> str:
        s = v.strip().upper()
        if not s:
            raise InvalidNumericalDataError("Signal symbol cannot be empty.")
        return s

    @field_validator("trigger_price", "suggested_stop_loss", "suggested_take_profit")
    @classmethod
    def validate_prices(cls, v: float) -> float:
        if not math.isfinite(v):
            raise InvalidNumericalDataError(f"Price must be finite (NaN/Inf prohibited), got {v}.")
        if v <= 0.0:
            raise InvalidNumericalDataError(f"Price must be strictly positive, got {v}.")
        return v

    @field_validator("timestamp_ms", "candle_timestamp_ms")
    @classmethod
    def validate_timestamps(cls, v: int) -> int:
        if v < 0:
            raise InvalidNumericalDataError(f"Timestamp must be non-negative, got {v}.")
        return v
