"""initial_schema

Revision ID: fb91b07df6bf
Revises: 
Create Date: 2026-09-03 13:12:30.118908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb91b07df6bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_trade_journals_client_order_id'), table_name='trade_journals')
    op.drop_index(op.f('ix_trade_journals_symbol'), table_name='trade_journals')
    op.drop_table('trade_journals')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('idx_snapshot_sym_tf_time'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_symbol'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_timestamp'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('risk_decisions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_decisions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risk_mode', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('max_position_size', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('approved_size', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('checks_passed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('checks_failed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('risk_decisions_signal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_decisions_pkey'))
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=24, scale=8), autoincrement=False, nullable=False),
    sa.Column('rvol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oi', sa.NUMERIC(precision=24, scale=8), autoincrement=False, nullable=True),
    sa.Column('funding_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cvd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('regime', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('market_snapshots_pkey'))
    )
    op.create_index(op.f('ix_market_snapshots_timestamp'), 'market_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_market_snapshots_symbol'), 'market_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('idx_snapshot_sym_tf_time'), 'market_snapshots', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('exchange_order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('order_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('stop_loss', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('take_profit', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_exchange_order_id'), 'orders', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('min_qty', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('step_size', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('tick_size', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('min_notional', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('symbols_pkey'))
    )
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('trade_journals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('setup_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('realized_pnl', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('risk_reward_achieved', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('exit_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confluence_reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_journals_pkey'))
    )
    op.create_index(op.f('ix_trade_journals_symbol'), 'trade_journals', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_journals_client_order_id'), 'trade_journals', ['client_order_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('setup', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entry_min', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('entry_max', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('stop_loss', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('take_profit', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('expected_rr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confluence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('regime', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('signals_pkey'))
    )
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    # ### end Alembic commands ###
